### ISSUE TITLE
Job Pods deleted on target clusters cause extra untracked Pods to be created

### ISSUE THREAD

**Issue by ahmetb** [admiraltyio/admiralty#149]
This one is pretty easy to reproduce.
Trying out quickstart https://admiralty.io/docs/quick_start but changed sleep seconds from 5 to something longer.
tl;dr I schedule 10 jobs, then delete one of the actual pods scheduled in kind-eu cluster, and note that even after deleting Jobs/Pods from kind-cd control plane, there's an untracked Pod/PodChaperon remaining in kind-eu forever and a Pending Pod in kind-us forever.

Repro steps:

```sh
for i in $(seq 1 10)
do
  cat <<EOF | kubectl --context kind-cd apply -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: global-$i
spec:
  template:
    metadata:
      annotations:
        multicluster.admiralty.io/elect: ""
    spec:
      containers:
      - name: c
        image: busybox
        command: ["sh", "-c", "echo Processing item $i && sleep 5000000"]
        resources:
          requests:
            cpu: 100m
      restartPolicy: Never
EOF
done
```

```
$ kubectl get pods --context=kind-cd
NAME              READY   STATUS    RESTARTS   AGE
global-1-s7v9x    1/1     Running   0          36s
global-10-7qngk   1/1     Running   0          34s
global-2-s2hpl    1/1     Running   0          36s
global-3-85hr9    1/1     Running   0          35s
global-4-s6vc9    1/1     Running   0          35s
global-5-grqwn    1/1     Running   0          35s
global-6-gh2hn    1/1     Running   0          35s
global-7-288jq    1/1     Running   0          35s
global-8-zgc2g    1/1     Running   0          35s
global-9-2qwwl    1/1     Running   0          35s
```

```
$ kubectl get pods --context=kind-eu
NAME                    READY   STATUS    RESTARTS   AGE
global-10-7qngk-267gj   1/1     Running   0          43s
global-2-s2hpl-kbzdd    1/1     Running   0          52s
global-4-s6vc9-gqt58    1/1     Running   0          50s
global-5-grqwn-5nqm6    1/1     Running   0          49s
global-7-288jq-h45sk    1/1     Running   0          46s
```
```
$ kubectl get pods --context=kind-us
NAME                   READY   STATUS    RESTARTS   AGE
global-1-s7v9x-g92mj   1/1     Running   0          54s
global-3-85hr9-v45jf   1/1     Running   0          52s
global-6-gh2hn-2q89w   1/1     Running   0          49s
global-8-zgc2g-wqf77   1/1     Running   0          46s
global-9-2qwwl-nmb7v   1/1     Running   0          45s
```

now, I'll manually remove one of the pods in kind-eu, like `global-10-7qngk-267gj`, expecting a new one to be created.

```
$ kubectl delete pods global-10-7qngk-267gj --context=kind-eu
pod "global-10-7qngk-267gj" deleted
```

now, let's take a look at pods in `cd`  (no indication of this pod being deleted in `eu`):

```
NAME              READY   STATUS    RESTARTS   AGE
global-1-s7v9x    1/1     Running   0          2m5s
global-10-7qngk   1/1     Running   0          2m3s
...
```

but now, there are multiple Pods for global-10-* in kind-eu (expecting only one to exist):

```
$ kubectl get pods --context=kind-eu
NAME                    READY   STATUS    RESTARTS   AGE
global-10-4xvgt-f7lhg   1/1     Running   0          30s
global-10-7qngk-267gj   1/1     Running   0          31s
global-2-s2hpl-kbzdd    1/1     Running   0          2m36s
global-4-s6vc9-gqt58    1/1     Running   0          2m34s
global-5-grqwn-5nqm6    1/1     Running   0          2m33s
global-7-288jq-h45sk    1/1     Running   0          2m30s
```

This seems to be a bug.

By doing this, a pod named `global-10-4xvgt-*` also exists in kind-us now (did not expect the pod to get to this cluster)

```
kubectl get pod --context=kind-us
NAME                    READY   STATUS        RESTARTS   AGE
...
global-10-4xvgt-g8nn8   0/1     Pending       0          3m33s
```
but it's waiting indefinitely:
```
Events:
  Type     Reason            Age    From                 Message
  ----     ------            ----   ----                 -------
  Warning  FailedScheduling  4m30s  admiralty-candidate  running PreBind plugin "candidate": timed out waiting for the condition
  Warning  FailedScheduling  3m58s  admiralty-candidate  running PreBind plugin "candidate": timed out waiting for the condition
```

The Job on `kind-cd` control plane actually seems to notice both `global-10-4xvgt`  and `global-10-7qngkj`:
```
kubectl describe job --context=kind-cd global-10
...
Events:
  Type    Reason            Age    From            Message
  ----    ------            ----   ----            -------
  Normal  SuccessfulCreate  3m22s  job-controller  Created pod: global-10-7qngk
  Normal  SuccessfulCreate  78s    job-controller  Created pod: global-10-4xvgt
```

but I believe it can't do anything such as cleaning the duplicate job pod, because it doesn't show up in kind-cd control plane:

```
$ kubectl get pod --context=kind-cd
NAME              READY   STATUS    RESTARTS   AGE
global-1-s7v9x    1/1     Running   0          4m23s
global-10-7qngk   1/1     Running   0          4m21s
global-2-s2hpl    1/1     Running   0          4m23s
```

so now, I'll delete all Jobs (on kind-cd). But some pods are never cleaned up in `us`/`eu` clusters:

```
{⎈ |kind-cd:default} ~ $ kubectl get pod --context=kind-cd
No resources found in default namespace.
{⎈ |kind-cd:default} ~ $ kubectl get pod --context=kind-us
NAME                    READY   STATUS    RESTARTS   AGE
global-10-4xvgt-g8nn8   0/1     Pending   0          7m18s
{⎈ |kind-cd:default} ~ $ kubectl get pod --context=kind-eu
NAME                    READY   STATUS    RESTARTS   AGE
global-10-4xvgt-f7lhg   1/1     Running   0          7m23s
```

I suspect these will never go away because Job went away, so did the Pods in `cd` cluster. But the PodChaperons still exist:

```
{⎈ |kind-cd:default} ~ $ kubectl get podchaperon --context=kind-eu
NAME                    RESERVED   ALLOWED
global-10-4xvgt-f7lhg   true       true
{⎈ |kind-cd:default} ~ $ kubectl describe podchaperon --context=kind-eu
...
Events:
  Type    Reason  Age                    From       Message
  ----    ------  ----                   ----       -------
  Normal  Synced  8m15s (x4 over 8m19s)  admiralty  PodChaperon synced successfully
```

**Comment by adrienjt** [comment]
Hi @ahmetb, thank you for your detailed bug report. I am actually unable to exactly repro, but I think I know why.

When I delete a delegate pod in kind-eu, it is recreated by its PodChaperon. This is currently the expected behavior, as discussed here: https://github.com/admiraltyio/admiralty/pull/145#issue-1155765620. The proxy pod in kind-cd isn't deleted, but its status, which reflects the status of the PodChaperon's current delegate pod, goes through terminating, then pending again. I believe this is the root cause, because it breaks a Kubernetes invariant (see below when the Job controller sees too many active pods). It would become running again if the proxy pod wasn't deleted by the job controller, thereby cascade deleting the PodChaperon and delegate pod.

> When a Pod fails, then the Job controller starts a new Pod.
https://kubernetes.io/docs/concepts/workloads/controllers/job/#handling-pod-and-container-failures

When global-10-7qngk appears to have failed, the Job controller creates global-10-4xvgt in kind-cd. Soon after, global-10-7qngk appears to have just started again. There are too many active job pods, so the Job controller deletes one of them.

// activePodsForRemoval returns Pods that should be removed because there
// are too many pods running [...].
// Sorts candidate pods in the order such that not-ready < ready, unscheduled
// < scheduled, and pending < running. This ensures that we delete pods
// in the earlier stages whenever possible
https://github.com/kubernetes/kubernetes/blob/44e5bc0f30cfddec6d053edf146f8657f838c4c3/pkg/controller/job/job_controller.go#L892-L897

The two pods are racing. When I tried, the Job controller decided to delete the old pod (both must have been running already), and its PodChaperon and new delegate pod were successfully cascade deleted. In your case, it decided to delete the new one (still pending), and, due to some bug, its PodChaperons and candidate pods in both clusters weren't cascade deleted.

Proxy pods are created with finalizers to ensure that PodChaperons and candidate/delegate pods are deleted: https://github.com/admiraltyio/admiralty/blob/331021bf73d6db840c98674af6063174396186f7/pkg/webhooks/proxypod/proxypod.go#L157-L168

I still need to figure out why that didn't work.

**Comment by adrienjt** [comment]
Here's the problem: https://github.com/admiraltyio/admiralty/blob/331021bf73d6db840c98674af6063174396186f7/pkg/controllers/feedback/controller.go#L139-L166

`candidate` is gotten from a lister, which can be stale.

1. job controller creates proxy pod, pending
2. proxy scheduler creates candidate pod in each target
3. proxy scheduler Reserve plugin is called, so one candidate is allowed to run, in kind-eu
4. job controller deletes proxy pod, terminating
5. proxy scheduler PostBind plugin isn't called, so failed candidate in kind-us isn't deleted
6. feedback controller reconciles proxy pod, doesn't see candidates yet (stale lister), so removes finalizers

Short term, we should use a client rather than a lister to get the candidate in the feedback controller. This will fix the bug. Would you like to take a stab at it?

We may also want to ensure that the proxy scheduler does not create a candidate pod if the corresponding finalizer is missing already. This would solve another race condition that I haven't observed, if it is at all possible.

Longer term, we should implement the proposal discussed in https://github.com/admiraltyio/admiralty/pull/145#issue-1155765620, i.e., only recreate delegate from PodChaperon if connection with source is lost, to avoid breaking the Kubernetes invariant that the job controller assumes, which is that a failed pod should not restart.
