### ISSUE TITLE
Does Admirality support Open ID Connect - OIDC

### ISSUE THREAD

**Issue by benswinney** [admiraltyio/admiralty#73]
I'm trying to deploy Admirality to IBM Kubernetes Service (IKS) (IBM Cloud) and an On-Premise Datacenter (x86).

When I attempt to register the cluster with Admirality, it returns the following error message:

![Screen Shot 2020-09-30 at 11 44 27 am](https://user-images.githubusercontent.com/24420825/94634029-4f51fd00-0312-11eb-8e4f-f0007061778a.png)

IBM Cloud uses Open ID Connect, does Admirality support this?

**Comment by adrienjt** [comment]
Hi @benswinney, we forgot to import client-go auth plugin libraries (oidc, azure, gcp, openstack): https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/plugins.go

Our test setup used either certificates or exec plugins (e.g. aws), which don't require explicit imports.

This is fixed in v0.11.1 of the Admiralty CLI. Please upgrade your CLI. No need to upgrade other components.
https://admiralty.io/docs/operator_guide/installation
