### ISSUE TITLE
GKE deployment

### ISSUE THREAD

**Issue by skalp** [admiraltyio/admiralty#74]
Hello,

I tried to deploy admiralty on two GKE clusters.

During virtual kubelet creation on source cluster, I get following error in node description:

Warning  FailedToCreateRoute  25m                  route_controller  Could not create route 0d3a65bd-97b9-4959-aa67-99874ab6317e 10.116.2.0/24 for node admiralty-plm-c7ff8eb6-target-cluster-3e3933bad4 after 233.845278ms: instance not found

The node is tainted as following:

Taints:             node.kubernetes.io/network-unavailable:NoSchedule
                    virtual-kubelet.io/provider=admiralty:NoSchedule

The pods deployed in a namespace with a multicluster.admiralty.io/elect: "" annotation set stay in Pending State.

Is GKE a supported target for multicluster scheduler deployment ?

Thanks

**Comment by skalp** [comment]
Answering myself, but if anyone get the issue:
if gke is configured as a routes based cluster, you'll get the error described above.
It works fine is gke is configured as a VPC native cluster.
Also, kubernetes >= 1.17 seems to be required to get v1.CSINode CRD support

**Comment by adrienjt** [comment]
Hi @skalp ,

Proxy pods tolerate both taints since #44 was fixed, so you shouldn't have any problem with routes-based GKE clusters.

> The pods deployed in a namespace with a multicluster.admiralty.io/elect: "" annotation set stay in Pending State.

The pods should be annotated with `multicluster.admiralty.io/elect=""`, and the namespace should be labeled with `multicluster-scheduler=enabled`. It's a little convoluted, but that's how the webhook selects pods for now. We'll simplify soon.

Regarding CSINode support, please refer to #19. We actually just published a scheduler image that works with 1.16 (and maybe older versions). So you can override the image tag for the proxy-scheduler and candidate-scheduler deployments with `0.11.0-k1.16` and add `, "--feature-gates", "CSINodeInfo=false""` to their args arrays.

The requirement for Kubernetes >=1.17 disappeared in the revamped documentation. I'll make sure it's clearer.

**Comment by skalp** [comment]
@adrienjt Thanks for the clarifications
